### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by pepa65** [shiro/map2#3]
`cat q.m2`:
```
a::b;
```
`RUST_BACKTRACE=1 ./target/release/map2 q.m2`:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Permission denied (os error 13)', /home/pp/git/map2/src/device/virtual_input_device.rs:110:76
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
   2: core::result::unwrap_failed
             at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::runtime::task::core::Core<T,S>::poll
   5: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: std::thread::local::LocalKey<T>::with
   8: tokio::runtime::thread_pool::worker::Context::run_task
   9: tokio::runtime::thread_pool::worker::Context::run
  10: tokio::macros::scoped_tls::ScopedKey<T>::set
  11: tokio::runtime::thread_pool::worker::run
  12: tokio::runtime::task::core::Core<T,S>::poll
  13: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  14: tokio::runtime::task::harness::Harness<T,S>::poll
  15: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by shiro** [comment]
Hmm, seems like you don't have write access to the device descriptor. Try `chmod 777 FILE_DESCRIPTOR_PATH` or run it as super user. If it works you can add an udev rule later, so that the permissions will be set automatically on device mount.
I'll update the README once you manage to fix it.

**Comment by pepa65** [comment]
No errors now when building, `cargo build --release`:
```
   Compiling map2 v0.1.0 (/home/pp/git/map2)
    Finished release [optimized] target(s) in 19.41s
```
Now: `sudo chmod 777 /dev/input/by-id/usb-Logitech_USB_Receiver-if01-event-kbd`
`RUST_BACKTRACE=full ./target/release/map2 q.m2`:
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Permission denied (os error 13)', /home/pp/git/map2/src/device/virtual_input_device.rs:110:76
stack backtrace:
   0:     0x556eee53f8bc - std::backtrace_rs::backtrace::libunwind::trace::h87bbdc8ae314e5a4
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x556eee53f8bc - std::backtrace_rs::backtrace::trace_unsynchronized::h779de2081f0fe77d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x556eee53f8bc - std::sys_common::backtrace::_print_fmt::h7f9f27f2b4d4cdf1
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:79
   3:     0x556eee53f8bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf95d19d7937b7307
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:58
   4:     0x556eee577abf - core::fmt::write::h31ddd5324183dd8d
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/fmt/mod.rs:1082
   5:     0x556eee538e77 - std::io::Write::write_fmt::h6553ae225ae21934
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/io/mod.rs:1514
   6:     0x556eee556f10 - std::sys_common::backtrace::_print::h6d7cde6fb59a3272
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:61
   7:     0x556eee556f10 - std::sys_common::backtrace::print::h024fb5a1f254b027
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:48
   8:     0x556eee556f10 - std::panicking::default_hook::{{closure}}::h008654930ff7c19c
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:200
   9:     0x556eee556c6e - std::panicking::default_hook::h611ef89f1ca4afb7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:219
  10:     0x556eee5574f3 - std::panicking::rust_panic_with_hook::h4dfeaf97568ec250
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:569
  11:     0x556eee53fcf9 - std::panicking::begin_panic_handler::{{closure}}::hf55586f621f9c415
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:476
  12:     0x556eee53fa0c - std::sys_common::backtrace::__rust_end_short_backtrace::hbddda20e4c1f6fd7
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys_common/backtrace.rs:153
  13:     0x556eee557102 - rust_begin_unwind
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/panicking.rs:475
  14:     0x556eee5773e1 - core::panicking::panic_fmt::he4c3f055751e8cea
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/panicking.rs:85
  15:     0x556eee577473 - core::result::unwrap_failed::h24cfbc9782f4fe17
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/core/src/result.rs:1220
  16:     0x556eee34675c - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h3cfc0bfdc5b8d570
  17:     0x556eee367b82 - tokio::runtime::task::core::Core<T,S>::poll::hddafc5b249f8e3f2
  18:     0x556eee36a2e7 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h9ff9e4c010c0efe9
  19:     0x556eee33c12f - tokio::runtime::task::harness::Harness<T,S>::poll::hed5d81549da6c0a1
  20:     0x556eee480a21 - std::thread::local::LocalKey<T>::with::h406af0694bda57af
  21:     0x556eee49e69e - tokio::runtime::thread_pool::worker::Context::run_task::h1f986d3e04019a0a
  22:     0x556eee49d830 - tokio::runtime::thread_pool::worker::Context::run::h01187a9238f0a3b9
  23:     0x556eee491bb3 - tokio::macros::scoped_tls::ScopedKey<T>::set::hb27e1842f4770be9
  24:     0x556eee49d24e - tokio::runtime::thread_pool::worker::run::had8e1d2d90726bf2
  25:     0x556eee49a51b - tokio::runtime::task::core::Core<T,S>::poll::h882ea9e454b9db57
  26:     0x556eee4a4b23 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h2fe2496ae4a870a3
  27:     0x556eee4a7dc3 - tokio::runtime::task::harness::Harness<T,S>::poll::hc10aa5b26c9908cf
  28:     0x556eee494209 - tokio::runtime::blocking::pool::Inner::run::hf7904a21d5eac087
  29:     0x556eee4807ce - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c3f52869988841f
  30:     0x556eee48e7e6 - core::ops::function::FnOnce::call_once{{vtable.shim}}::he41aeaa3b0e1f987
  31:     0x556eee557f08 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h82ab465ddb64eba2
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/alloc/src/boxed.rs:1042
  32:     0x556eee557f08 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h5aa0c3a5cb1c92ed
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/alloc/src/boxed.rs:1042
  33:     0x556eee557f08 - std::sys::unix::thread::Thread::new::thread_start::ha82b07ed1fc4982c
                               at /build/rustc-n7HJ8w/rustc-1.47.0+dfsg1+llvm/library/std/src/sys/unix/thread.rs:87
  34:     0x7f867e0d3609 - start_thread
  35:     0x7f867dfdf293 - clone
  36:                0x0 - <unknown>
```
What I also find strange is that the process hangs and doesn't return to the shell until I press Ctrl-C.

**Comment by shiro** [comment]
The issue seems to be with the new virtual output device we're creating rather than grabbing the input descriptors...
Sorry to bother you, but could you try again with the latest master (after a0ed9d5), I added more verbose error reporting.

**Comment by pepa65** [comment]
After building latest and `sudo chmod 777 /dev/uinput` it just hangs, and if I press `a`, it echoes `a`.

**Comment by shiro** [comment]
Alright, so it no longer fails to spawn an output device, that's good news at least.
Are you grabbing the right input device in the device list (`-d argument`), it seems to work but not actually grab your device... (to remap your keyboard you'll need to find the keyboard file descriptor in `/dev/input` and specify it in the device list.)

**Comment by pepa65** [comment]
I am now trying: `RUST_BACKTRACE=full ./target/release/map2 q.m2 -d /dev/input/by-id/usb-Logitech_USB_Receiver-if01-event-kbd`:
`Error: failed to parse devices file: stream did not contain valid UTF-8`

**Comment by shiro** [comment]
Oh, there's been a misunderstanding about the device fd ^^, I'll update the README later to make it clearer.

- make a file called `devices.list` (or whatever else)
- write the fd's you want to grab into it (or regex patterns)
- `map2 -d device.list ...`

**Comment by pepa65** [comment]
OK, that does something..! It does emit a fair number of newlines on the terminal, but it also does seem to do what I would expect. Even when I moved the focus to this window to type this message, it started off with at least 20 of them. But for the rest it seems to insert itself where it should.
Any idea about the newlines?


































































aabbb

**Comment by shiro** [comment]
yeah, since the terminal command is run as soon as you push down your enter key, map2 grabs the keyboard, so if you release the enter key right away the 'enter up' event won't get registered so you have to press enter again after it's grabbed.
This isn't really a bug, but a consequence of grabbing the device and there's not much I can do about it. (if you don't run map2 from the terminal you don't have that issue for example).

I'll close this ticket here since your issue is resolved :) (and I'll describe the enter behaviour to the README for other people)
